### ISSUE TITLE
Implement unlocking animation

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/osk-sdl#20]
This depends on #15.

I can probably make the dots move while unlocking with some animation code. Like implement a "wave" by moving the dots up and down with a delay between them..

**Comment by craftyguy** [comment]
39e54addf191045b67a3744d724a17a15056faa1 should allow for implementing an unlocking animation

**Comment by craftyguy** [comment]
closed via e42b9f271fdd34b1fc7efd546c71352acc3a987b
