### ISSUE TITLE
Generate object files in the Makefile, so distcc works

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/osk-sdl#26]
The linking stage can not be done over distcc, so you can only use the cross-compiler when you compile objects from your cpp files, and link them at the end. I can help rewriting the `Makefile` if necessary, just let me know!

Right now, the compiling process happens in QEMU only (which isn't that noticeable because of the small code size).

**Comment by craftyguy** [comment]
Help is appreciated, since Makefiles are still very much a magical mystery to me

**Comment by ollieparanoid** [comment]
@craftyguy wrote in https://github.com/postmarketOS/pmbootstrap/pull/476#issuecomment-326164879:

> It seems that, based on your comments, #26 will help with compilation speed? 
> If so, I can take a shot at implementing this ASAP, but doesn't it require 
> rewriting the Makefile(s) for SDL2 and directfb? If so, I'm not sure I want to 
> go there...

No, that only applies to the osk-sdl Makefile, and it will save a minute maximum 
in compilation time, so that's not worth looking into with priority right now.

**Comment by craftyguy** [comment]
Closed via e0a2a98fdc191af354b8fd78f249189be83951cf
