### ISSUE TITLE
Upstream osk-sdl dependencies to Alpine

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/osk-sdl#33]
This is about upstreaming the dependencies that we need for our on screen keyboard. Tagging @ncopa, @kaniini, @AmatCoder as you are listed in the git changelog of Alpine's `sdl2` aport.

Relevant packages:
```
- sdl2 (forked from Alpine to add `directfb` dependency)
  - directfb (new)
    - tslib (new)
```

@craftyguy wrote in https://github.com/postmarketOS/pmbootstrap/pull/476#issuecomment-326164879:
> Honestly, I'm not sure about the upstreaming part. Getting directfb "good enough" for osk-sdl may not result in a configuration for directfb that would make it useful for other developers to use in alpine for other things. Maybe I'm being overly cautious on how this would be accepted (or not) by upstream since I have no experience working with the Alpine developers.

Dear **Alpine developers**, as far as I know, it is not an issue if we just support our own use-case for now, and other people adjust the packages to their use-case if necessary. Is that right?

Our `directfb` [config](https://github.com/postmarketOS/pmbootstrap/blob/1df0a6d2ed92eae9692dc86ba2e36e170b26ae8e/aports/main/directfb/APKBUILD#L55-L67):
```
    ./configure --prefix=/usr \
                --sysconfdir=/etc \
                --enable-static \
                --disable-zlib \
                --disable-x11 \
                --enable-fbdev \
                --disable-vnc \
                --disable-osx \
                --disable-mesa \
                --enable-drmkms \
                --enable-freetype \
                --with-inputdrivers=input_hub,keyboard,linuxinput,ps2mouse,serialmouse,tslib \
                --with-gfxdrivers=omap,vmware,mach64
```

*I really prefer if we upstream our stuff, so we don't carry around duplicate work, and we might actually help Alpine by sharing the maintenance effort. Also until our own binary repo is finished, we can save fellow postmarketOS developers of spending unnecessary time compiling these dependencies.*

If everyone agrees on this, this is how I suggest we do it (*I can help upstreaming if necessary!*):
- [x] Upstream tslib
- [x] Upstream directfb
- [x] Upstream SDL2 changes

**Comment by ncopa** [comment]
I think upstreaming directfb and tslib with your needed config is ok, and I think sdl2 is modular so I don't think that will be a problem. I suggest that you create PR's and we can discuss how we want each pkg there.

**Comment by craftyguy** [comment]
directfb submitted: https://lists.alpinelinux.org/alpine-aports/4908.html
