### ISSUE TITLE
Letter alignment on keys

### ISSUE THREAD

**Issue by antonok-edm** [postmarketOS/osk-sdl#36]
Letter size (and positioning) should be scaled dynamically based on screen size. They seem to be center-aligned horizontally, but are aligned to the top of the key vertically. On large screens, this will result in awkwardly spaced, difficult to read letters.

**Comment by MartijnBraam** [comment]
the letter size is scaled to screen size currently so the only alignment is is that the letters are aligned slightly to the top of the key. Vertically centering the letter should be easy, this isn't css after all.

**Comment by craftyguy** [comment]
Closed via 8c3517cdc45b7585325af3fcdb4e9dbd5ddb09cf
