### ISSUE TITLE
Move license to GPLv3

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/osk-sdl#45]
@MartijnBraam & @IanS5 

I would like to move the license for this project from MIT to GPLv3 (mainly to allow for easier re-use of other GPL'd code).

Both of you have contributed code to this project, so I need your agreement before moving forward! Please reply with a "yay" or "nay".

**Comment by MartijnBraam** [comment]
yay

**Comment by craftyguy** [comment]
@IanS5  ?

**Comment by IanS5** [comment]
yay

**Comment by craftyguy** [comment]
Closed via cc76358c7b78cda5dbb762d45f923289144418ef


![2017-09-08_875x770_scrot](https://user-images.githubusercontent.com/1474209/30235347-06e67760-94bd-11e7-90dc-f3e568a37fc7.png)
