### ISSUE TITLE
osk-sdl does not work with lg-mako

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/osk-sdl#47]
As reported yesterday in the chat: I get a blackscreen, and the screen flickers gray/white? ever 10th second or so. I've installed the usb-shell hook, and noticed that the osk-sdl is constantly restarting.
Here is what /osk-sdl.log says:
```
commandline read: osk-sdl
commandline read: -n
commandline read: root
commandline read: -d
commandline read: /dev/dm-1
commandline read: -c
commandline read: /etc/osk.conf
commandline read: -v
(*) Direct/Thread: Started 'SigHandler' (23976) [CRITICAL - OTHER/0] <85316>...

   ~~~~~~~~~~~~~~~~~~~~~~~~~| DirectFB 1.7.7 |~~~~~~~~~~~~~~~~~~~~~~~~~~
        (c) 2012-2015  DirectFB integrated media GmbH
        (c) 2001-2015  The world wide DirectFB Open Source Community
        (c) 2000-2004  Convergence (integrated media) GmbH
      ----------------------------------------------------------------

(*) DirectFB/Core: Single Application Core. (2017-09-08 22:49)
(*) Direct/Memcpy: Using libc memcpy()
(*) Direct/Thread: Started 'Fusion Dispatch' (23977) [MESSAGING - OTHER/0] <85316>...
(*) Direct/Thread: Started 'VT Switcher' (23980) [CRITICAL - OTHER/0] <85316>...
(*) Direct/Thread: Started 'VT Flusher' (23981) [DEFAULT - OTHER/0] <85316>...
(*) DirectFB/FBDev: Found 'msmfb44_80601' (ID 0) with frame buffer at 0x8231e000, 11520k (MMIO 0x00000000, 0k)
(*) Direct/Modules: suppress module 'linux_input'
(*) Direct/Thread: Started 'Keyboard Input' (23982) [INPUT - OTHER/0] <85316>...
(*) DirectFB/Input: Keyboard 0.9 (directfb.org)
(*) DirectFB/Input: Hot-plug detection enabled with Input Hub Driver
(*) Direct/Thread: Started 'tslib Input' (23983) [INPUT - OTHER/0] <85316>...
(*) DirectFB/Input: tslib touchscreen 0 0.1 (tslib)
(*) DirectFB/Graphics: Generic Software Rasterizer 0.7 (directfb.org)
(!) DirectFB/FBDev: No supported modes found in /etc/fb.modes and current mode not supported!
(!) DirectFB/FBDev: Current mode's pixelformat: rgba 8/24, 8/16, 8/8, 8/0 (32bit)
(!) DirectFB/Core/layers: Failed to initialize layer 0!
    --> A general initialization error occured
(!) DirectFB/Core: Could not initialize 'layer_core' core!
    --> A general initialization error occured

```

**Comment by craftyguy** [comment]
Try dropping this file into /etc: https://github.com/DirectFB/directfb/blob/master/fb.modes

I changed the directfb package yesterday to install this file to /etc,
and mkinitfs will add it to the initramfs. Martijn was having this
same issue and adding this file resolved it for him I believe.

**Comment by ollieparanoid** [comment]
Yeah I just realized that there were new commits. I've gotta go now. But I'll let the new stuff compile in the mean time and try it later/tomorrow. Thanks for the quick response! (I didn't manage to quickly copy the file over with nc :p)

**Comment by craftyguy** [comment]
In addition, you may have to add a custom mode to that file, e.g. from running `fbset` on the device to display mode for device.

**Comment by ollieparanoid** [comment]
with the latest version, this is the log output:
https://gist.github.com/ollieparanoid/220bbf986633e6b3084a0f16daf9e55d

I did not create the fb.modes file yet, will do that soon to debug this further. Thanks @craftyguy!

**Comment by AeternaMia** [comment]
This mode seems to work:
```
mode "768x1280-0"
	# D: 0.002 MHz, H: 0.002 kHz, V: 0.002 Hz
	geometry 768 1280 768 1280 16
	timings 453770000 180 8 22 8 4 2
	accel false
	rgba 8/24,8/16,8/8,8/0
endmode
```

**Comment by craftyguy** [comment]
[This commit to the 'add osk' branch in pmbootstrap](https://github.com/postmarketOS/pmbootstrap/commit/54c0e24e13852d554982e2358e1024cb44a4fd82) should add your custom mode and also fix the touchscreen issue that @AeternaMia reported in matrix.

Please test!

**Comment by AeternaMia** [comment]
After adding `deviceinfo_dev_touchscreen="/dev/input/event2"` to the deviceinfo I have successful unlock on lg-mako with osk-sdl!

The background is pink instead of blue (and this continues to be the case after booting as many times as I stop and start osk-sdl again) but at the moment this is a purely cosmetic issue.
I tried commenting out the `rgba` line from the `fb.modes` line above and that did not make a difference (after boot)

**Comment by craftyguy** [comment]
Great! Thanks for testing!

We can add that deviceinfo var to the mako package, I should have done it with the other changes I made but forgot to.

**Comment by AeternaMia** [comment]
Also I had to fix the APKBUILD for device-lg-mako:

```
+++ b/aports/device/device-lg-mako/APKBUILD
@@ -26,12 +26,12 @@ package() {
        install -D -m644 "$srcdir"/profile.sh \
                "$pkgdir"/etc/profile.d/00-$pkgname.sh
        install -D -m644 "$srcdir"/pointercal \
-               "$pkgdir" /etc/pointercal
+               "$pkgdir"/etc/pointercal
        install -D -m644 "$srcdir"/fb.modes \
-               "$pkgdir" /etc/fb.modes
+               "$pkgdir"/etc/fb.modes
 }
```

**Comment by craftyguy** [comment]
Fixed both the typos in the APKBUILD and added deviceinfo_dev_touchscreen info to deviceinfo for Mako. 

I'm going to close this now based on @AeternaMia's input, but @ollieparanoid, if you continue to have issues with this then please re-open!
