### ISSUE TITLE
[hammerhead] directfb mode issue

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/osk-sdl#49]
I've got this working on the hammerhead with the info on the debugging wiki page.
The current mode I use, which is not the same as `fbset -s`:

```
mode "1080x1920-1"
        # D: 1.243 MHz, H: 1.142 kHz, V: 0.593 Hz
        geometry 1080 1920 1080 1920 16
        timings 804667 2 4 2 2 2 2
        accel false
        rgba 5/11,6/5,5/0,0/0
endmode
```

The hammerhead has still the not-refreshing issue. Apparently this is not really a bug but the way this driver does double buffering, sadly directfb doesn't support this double buffer method yet.

Thanks to zhuowei on IRC we now know that in the android recovery they flip the buffer like this: https://github.com/LineageOS/android_bootable_recovery/blob/6a0693fcce0fea8fd41252ba176aa8e3de33b953/minui/graphics_fbdev.cpp#L77

which is basically the same thing as doing `cat mode > mode`.

3 possible options for making this work:

1. Add a workaround flag to osk-sdl that does that ioctl on the framebuffer device in the render loop
1. Add this refreshing method to directfb somewhere
1. Write a DRM driver for hammerhead

**Comment by craftyguy** [comment]
Does the patch [mentioned here](https://github.com/postmarketOS/pmbootstrap/issues/375) work on the 0.48 release of osk-sdl (without the workaround I submitted being applied to osk) ?

**Comment by drebrez** [comment]
@MartijnBraam @craftyguy do you think this can be closed? it should be solved with the `msm_fb_refresher` or do you actually want to add the same `ioctl` calls directly in `osk-sdl`?

**Comment by craftyguy** [comment]
I'm OK with closing it if it's no longer a problem because msm_fb_refresher can be used instream. I don't have a device that needs msm_fb_refresher, so I was not able to personally reproduce this original issue. Also, I didn't really want to do the same ioctl from within osk-sdl.. that was a hack/experiment.

**Comment by MartijnBraam** [comment]
This is fixed with the msm refresher right now (and maybe completely avoided whene mainline runs :D)
