### ISSUE TITLE
Keyboard is not drawn at the bottom of the screen

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/osk-sdl#55]
From @drebrez :

something I forgot to ask, why the keyboard is not completely attached to the bottom of the screen? 
In this video you see it clearly => http://i.imgur.com/kyDix4u.gifv
Maybe is the  `0, 1` location of the keyboard [here](https://github.com/postmarketOS/osk-sdl/blob/master/main.cpp#L218)?

**Comment by craftyguy** [comment]
@drebrez it's not from the initialization that you pointed to, the 0 and 1 represent 0% (starting position) and 100% (final position after start animation has finished), essentially.

I'm not sure why it doesn't draw it completely on the bottom of the screen, I'll have to look into it..

**Comment by MartijnBraam** [comment]
I've noticed that before, I guess I've made a off-my-one error on this line:

https://github.com/postmarketOS/osk-sdl/blob/master/keyboard.cpp#L119

**Comment by craftyguy** [comment]
Yea that's exactly what it is
