### ISSUE TITLE
No available video device

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/osk-sdl#68]
I'm [porting](https://wiki.postmarketos.org/wiki/Osk-sdl#Porting_to_New_Devices) osk-sdl to my device Motorola Moto G 2014 (titan).

Unfortunately when I run osk-sdl I get the following error

```
localhost:/home/pablo# osk-sdl -d a -n a -c /etc/osk.conf -v
ERROR: SDL_Init failed: No available video device
```

I haven't found anything related in the wiki nor in the issues. Any idea?

**Comment by ollieparanoid** [comment]
@magmastonealex has the same error, and he his framebuffer device is `/dev/fb0`. Just in case, it is also the framebuffer device for the `titan`, right? If not, you could pass `fbdev=...` to the `DFBARGS` ([source](https://linux.die.net/man/5/directfbrc)).

**Comment by PabloCastellano** [comment]
Yes, my framebuffer device is at `/dev/fb0`

**Comment by magmastonealex** [comment]
Just to record what I've discovered so far:

- Setting `SDL_VIDEODRIVER=directfb` results in `ERROR: SDL_Init failed: directfb not available`.
- My fb.modes file exist and seems to be valid
- Copying over debug utilities from the `directfb` alpine package:
    - Utilities all run - so no linking issues
    - Utilities can successfully initialize the screen, so there's no problem with the fb.modes settings.

This is on a samsung-i747m (Galaxy S3 USA/Canada version), which I'm currently porting.

**Comment by craftyguy** [comment]
Which version of osk-sdl?

**Comment by magmastonealex** [comment]
The version currently packaged with pmbootstrap: 0.50.

**Comment by craftyguy** [comment]
Thanks. Also, just to confirm, you are NOT running some other UI in
parallel (e.g. not running weston), correct? I've seen  directfb do
weird things if it detects something like weston running.

**Comment by magmastonealex** [comment]
No, no other UI running. This issue happens in both initramfs & when booted into pmOS.

I've just tried with 0.51, and it has the same result. I'm happy to test any ideas you have.

**Comment by craftyguy** [comment]
@magmastonealex thanks for the hint on this in IRC/matrix.

The issue is that upstream Alpine has updated SDL2 to 2.0.7, but they didn't add the directfb flag, so SDL2 in Alpine does NOT have directfb support. I have submitted a PR to Alpine to re-add this back in: https://github.com/alpinelinux/aports/pull/2654

**Comment by craftyguy** [comment]
Alpine has updated the SDL2 package to include directfb now. This issue should now be resolved!
