### ISSUE TITLE
osk-sdl blank display on honami

### ISSUE THREAD

**Issue by moondeck** [postmarketOS/osk-sdl#76]
When i run `osk-sdl -d a -n a -c /etc/osk.conf -v` osk-sdl seems to run, but the screen is blanked and nothing is shown. When i `Ctrl-C` it, weird things happen on the screen, the colors and scaling are off, the system becomes unusable.

Tested on Xperia Z1 (honami) with XFCE from the repo.

**Comment by ollieparanoid** [comment]
Could you share the log output of `osk-sdl`?
And did you run it inside xfce4 (since you mentioned it), or from the initramfs?

Thanks for opening the issue!

**Comment by moondeck** [comment]
https://gist.github.com/moondeck/3d1030d5499bc049fe2f033b6013761e Here. I ran it from the ssh console. XFCE4 was running on the phone.

**Comment by ollieparanoid** [comment]
Thanks for sharing the log!
From reading the [osk-sdl porting guide](https://wiki.postmarketos.org/wiki/Osk-sdl#Porting_to_New_Devices), the initial port is meant to be done with UI set to `none` in init, and also running it with a few variables exported. Does it work when you try step by step as described in this guide?

**Comment by craftyguy** [comment]
@moondeck as pointed out by @ollieparanoid, you really want to be testing osk-sdl without any other graphical applications running (e.g. X server + XFCE). osk-sdl is not meant to be run alongside other things that are using the gpu, and if it is then it'll likely result in some strange behavior since osk-sdl will be competing for resources with X/wayland/whatever.

**Comment by moondeck** [comment]
Sorry, totally missed that. What could be a possible on-screen alternative for XFCE then?

**Comment by ollieparanoid** [comment]
`matchbox-keyboard`:
https://postmarketos.org/static/img/2017-12/xfce4-i9505.jpg

**Comment by moondeck** [comment]
Now, that is what i am looking for.
