### ISSUE TITLE
Using squash and merge by default?

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/osk-sdl#8]
In `pmbootstrap` we're using "squash and merge", which always makes one commit when merging a PR. I prefer it for the following reasons:
* Shows the person who wrote the code and the person who merged the code in one commit: [example](https://github.com/postmarketOS/pmbootstrap/commits/master)
* Cleaner commits
* Git bisect actually works, you never end up getting a commit that doesn't work because it is from a PR that was only half way through.

If you guys agree, I could disable the other merge options and make "squash and merge" default.

**Comment by craftyguy** [comment]
I agree with this. I always try to squash my commits into one for a PR, with some rare exceptions. The migrate to SDL2 brand was a bit of a mess.

**Comment by MartijnBraam** [comment]
Yeah sounds good, works fine for pmbootstrap, should work fine here.

**Comment by ollieparanoid** [comment]
Ok, done! I've also disabled the "projects" feature, because we don't use that in `pmbootstrap` either. If you need it, just let me know.
